"""Compare R and Python SpaNorm outputs on shared data.

Loads the same data generated by R, runs Python SpaNorm, and compares.
"""

import numpy as np
import pandas as pd
import time
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")


def load_shared_data():
    """Load data generated by R. R saves as (ngenes, ncells), keep that format."""
    counts = pd.read_csv(os.path.join(DATA_DIR, "shared_counts.csv")).values.astype(np.float64)
    coords = pd.read_csv(os.path.join(DATA_DIR, "shared_coords.csv")).values
    return counts, coords  # Already (ngenes, ncells) from R


def load_r_results():
    """Load R reference results."""
    logcounts = pd.read_csv(os.path.join(DATA_DIR, "r_logcounts.csv")).values
    gmean = pd.read_csv(os.path.join(DATA_DIR, "r_gmean.csv")).values.ravel()
    alpha = pd.read_csv(os.path.join(DATA_DIR, "r_alpha.csv")).values
    psi = pd.read_csv(os.path.join(DATA_DIR, "r_psi.csv")).values.ravel()
    W = pd.read_csv(os.path.join(DATA_DIR, "r_W.csv")).values
    bs_xy_bio = pd.read_csv(os.path.join(DATA_DIR, "r_bs_xy_bio.csv")).values
    bs_xy_ls = pd.read_csv(os.path.join(DATA_DIR, "r_bs_xy_ls.csv")).values

    with open(os.path.join(DATA_DIR, "r_time.txt"), 'r') as f:
        r_time = float(f.read().strip())

    r_idx = pd.read_csv(os.path.join(DATA_DIR, "r_sample_idx.csv")).values.ravel() - 1  # R is 1-indexed

    return {
        'logcounts': logcounts,
        'gmean': gmean,
        'alpha': alpha,
        'psi': psi,
        'W': W,
        'bs_xy_bio': bs_xy_bio,
        'bs_xy_ls': bs_xy_ls,
        'time': r_time,
        'r_idx': r_idx,
    }


def run_python_spanorm(counts, coords, r_W=None, r_bs_bio=None, r_bs_ls=None,
                        r_idx=None, sample_p=0.5, df_tps=2, max_iter=20, tol=1e-3):
    """Run SpaNorm in Python, optionally using R's spline bases for fair comparison."""
    from spanorm.spline import bs_tps
    from spanorm.nb_model import dnbinom_log

    ngenes, ncells = counts.shape

    # Scale coordinates (same as R)
    coords_scaled = np.zeros_like(coords)
    for i in range(2):
        col = coords[:, i]
        rng = col.max() - col.min()
        if rng > 0:
            coords_scaled[:, i] = (col - col.min()) / rng - 0.5

    # Build spline bases
    if r_bs_bio is not None and r_bs_ls is not None:
        # Use R's spline bases for exact comparison
        bs_xy_bio = r_bs_bio
        bs_xy_ls = r_bs_ls
        n_bio = bs_xy_bio.shape[1]
        n_ls = bs_xy_ls.shape[1]
    else:
        bs_xy_bio, (df_bio_x, df_bio_y) = bs_tps(coords_scaled[:, 0], coords_scaled[:, 1], df_tps)
        df_tps_ls_x = max(df_bio_x // 2, 1)
        df_tps_ls_y = max(df_bio_y // 2, 1)
        bs_xy_ls, _ = bs_tps(coords_scaled[:, 0], coords_scaled[:, 1], max(df_tps_ls_x, df_tps_ls_y))
        n_bio = bs_xy_bio.shape[1]
        n_ls = bs_xy_ls.shape[1]

    # Size factors
    LS = counts.sum(axis=0)
    LS = LS / LS.mean()
    logLS = np.log(np.maximum(1e-8, LS))

    # Build W
    if r_W is not None:
        W = r_W
    else:
        logLS_col = logLS.reshape(-1, 1)
        logLS_bs_ls = logLS_col * bs_xy_ls
        W = np.hstack([logLS_col, bs_xy_bio, logLS_bs_ls])

    nW = W.shape[1]

    # wtype
    wtype = np.empty(nW, dtype='<U10')
    wtype[0] = 'ls'
    wtype[1:1+n_bio] = 'biology'
    wtype[1+n_bio:1+n_bio+n_ls] = 'ls'

    # Sample cells
    if r_idx is not None:
        idx = r_idx
    else:
        nsub = int(round(sample_p * ncells))
        rng = np.random.default_rng(42)
        idx = rng.choice(ncells, size=nsub, replace=False)

    Y_sub = counts[:, idx]
    W_sub = W[idx, :]
    nW_sub = W_sub.shape[1]

    # Initialize
    gmean = np.mean(np.log(Y_sub + 1), axis=1)
    alpha = np.zeros((ngenes, nW_sub))
    alpha[:, 0] = 1.0

    # Method-of-moments dispersion
    psi = np.zeros(ngenes)
    for g in range(ngenes):
        v = np.var(Y_sub[g], ddof=1)
        m = np.mean(Y_sub[g])
        psi[g] = max((v - m) / max(m**2, 1e-10), 0.01)

    # IRLS
    loglik_prev = -np.inf
    for iteration in range(max_iter):
        lmu = np.clip(gmean[:, np.newaxis] + alpha @ W_sub.T, -50, 50)
        mu_hat = np.exp(lmu)

        # Log-likelihood
        ll = 0.0
        for g in range(ngenes):
            ll += np.sum(dnbinom_log(Y_sub[g:g+1], mu_hat[g:g+1], psi[g:g+1]))

        # Working response
        Z = lmu + ((Y_sub + 0.01) / (mu_hat + 0.01) - 1)

        # Update alpha
        sig_inv = 1.0 / (psi[:, np.newaxis] * np.exp(-lmu))
        sig_inv = np.clip(sig_inv, 0, 1e10)
        wt = np.mean(sig_inv, axis=0)
        wt = np.minimum(wt, np.quantile(wt, 0.98))

        b = ((Z - gmean[:, np.newaxis]) * wt[np.newaxis, :]) @ W_sub
        WtW = W_sub.T @ (wt[:, np.newaxis] * W_sub)

        lam = np.zeros(nW_sub - 1)
        lam[wtype[1:] == 'biology'] = 0.0001 * ncells
        lam[wtype[1:] == 'ls'] = 0.0001 * ncells

        reg_mat = np.zeros((nW_sub, nW_sub))
        reg_mat[1:, 1:] = np.diag(lam)
        alpha_new = b @ np.linalg.inv(WtW + reg_mat)
        alpha_new[:, 0] = np.mean(alpha_new[:, 0])

        # Check convergence
        lmu_new = np.clip(gmean[:, np.newaxis] + alpha_new @ W_sub.T, -50, 50)
        ll_new = 0.0
        for g in range(ngenes):
            ll_new += np.sum(dnbinom_log(Y_sub[g:g+1], np.exp(lmu_new[g:g+1]), psi[g:g+1]))

        print(f"  Py iter {iteration+1:2d}: loglik = {ll:.2f}")

        if iteration > 0 and abs(ll_new - ll) / max(abs(ll), 1) < tol:
            alpha = alpha_new
            print("  Python converged")
            break
        alpha = alpha_new

        # Update gmean
        Z_res = Z - alpha @ W_sub.T
        gmean = np.sum(Z_res * sig_inv, axis=1) / np.sum(sig_inv, axis=1)

    # Normalization (mean_bio)
    is_bio = wtype == 'biology'
    lmu_bio = np.clip(gmean[:, np.newaxis] + alpha[:, is_bio] @ W[:, is_bio].T, -50, 50)
    logcounts_py = np.log2(np.exp(lmu_bio))

    return logcounts_py, gmean, alpha, psi, W, wtype


def compare(r, py, name):
    """Compare two arrays."""
    r_flat = r.ravel()
    py_flat = py.ravel()

    corr = np.corrcoef(r_flat, py_flat)[0, 1]
    max_err = np.max(np.abs(r_flat - py_flat))
    mean_err = np.mean(np.abs(r_flat - py_flat))

    # Per-row correlation
    n_rows = r.shape[0]
    row_corrs = np.zeros(n_rows)
    for i in range(n_rows):
        if np.std(r[i]) > 0 and np.std(py[i]) > 0:
            row_corrs[i] = np.corrcoef(r[i], py[i])[0, 1]
        else:
            row_corrs[i] = 1.0 if np.allclose(r[i], py[i]) else 0.0

    print(f"\n  {name}:")
    print(f"    Overall correlation:  {corr:.6f}")
    print(f"    Max absolute error:   {max_err:.6e}")
    print(f"    Mean absolute error:  {mean_err:.6e}")
    print(f"    Per-row corr (mean):  {np.mean(row_corrs):.6f}")
    print(f"    Per-row corr (min):   {np.min(row_corrs):.6f}")

    return corr


def main():
    print("=" * 60)
    print("SpaNorm R vs Python Comparison")
    print("=" * 60)

    # Load shared data
    print("\nLoading shared data...")
    counts, coords = load_shared_data()
    print(f"  Data shape: {counts.shape[0]} genes x {counts.shape[1]} cells")

    # Load R results
    print("Loading R reference results...")
    r = load_r_results()
    print(f"  R time: {r['time']:.3f}s")

    # Run Python with R's spline bases (fair comparison)
    print("\nRunning Python SpaNorm (with R's spline bases)...")
    t0 = time.time()
    py_lc, py_gmean, py_alpha, py_psi, py_W, py_wtype = run_python_spanorm(
        counts, coords,
        r_W=r['W'], r_bs_bio=r['bs_xy_bio'], r_bs_ls=r['bs_xy_ls'],
        r_idx=r['r_idx'],
        sample_p=0.5, df_tps=2, max_iter=20, tol=1e-3
    )
    py_time = time.time() - t0
    print(f"  Python time: {py_time:.3f}s")

    # Compare
    print("\n" + "=" * 60)
    print("COMPARISON RESULTS")
    print("=" * 60)

    corr_lc = compare(r['logcounts'], py_lc, "logcounts")
    corr_gmean = compare(r['gmean'].reshape(1, -1), py_gmean.reshape(1, -1), "gmean")
    corr_alpha = compare(r['alpha'], py_alpha, "alpha")
    corr_psi = compare(r['psi'].reshape(1, -1), py_psi.reshape(1, -1), "psi")

    # Speed comparison
    print(f"\n  Speed:")
    print(f"    R time:      {r['time']:.3f}s")
    print(f"    Python time: {py_time:.3f}s")
    speedup = r['time'] / py_time if py_time > 0 else float('inf')
    print(f"    Speedup:     {speedup:.2f}x")

    # Gate check
    print("\n" + "=" * 60)
    print("GATE CHECK")
    print("=" * 60)

    passed = True
    if corr_lc > 0.96:
        print(f"  [PASS] logcounts correlation: {corr_lc:.6f} > 0.96")
    else:
        print(f"  [FAIL] logcounts correlation: {corr_lc:.6f} <= 0.96")
        passed = False

    if py_time < r['time']:
        print(f"  [PASS] Python faster: {py_time:.3f}s < {r['time']:.3f}s")
    else:
        print(f"  [WARN] Python slower: {py_time:.3f}s >= {r['time']:.3f}s")

    # Also run with Python's own spline bases
    print("\n" + "=" * 60)
    print("Running Python with its own spline bases...")
    t0 = time.time()
    py_lc2, _, _, _, _, _ = run_python_spanorm(
        counts, coords, sample_p=0.5, df_tps=2, max_iter=20, tol=1e-3
    )
    py_time2 = time.time() - t0
    corr_lc2 = compare(r['logcounts'], py_lc2, "logcounts (own splines)")
    print(f"  Python time (own splines): {py_time2:.3f}s")

    print("\n" + "=" * 60)
    if passed:
        print("OVERALL: PASS")
    else:
        print("OVERALL: NEEDS FIXING")
    print("=" * 60)


if __name__ == "__main__":
    main()
