"""
Notebook 1: Pipeline-level R vs Python Parity
==============================================
This script demonstrates the parity between R SpaNorm and py-SpaNorm.
Pre-execute and convert to .ipynb for release.
"""

# %% [markdown]
# # py-SpaNorm: R vs Python Pipeline Parity
#
# This notebook compares the output of R's SpaNorm with py-SpaNorm
# on the same input data, verifying numerical equivalence.

# %%
import numpy as np
import pandas as pd
import time
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# %% [markdown]
# ## 1. Load Shared Test Data
#
# Data generated by R (`r_generate_data.R`), shared between R and Python.

# %%
DATA_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data")

counts = pd.read_csv(f'{DATA_DIR}/large_counts.csv').values.astype(np.float64)
coords = pd.read_csv(f'{DATA_DIR}/large_coords.csv').values
r_lc = pd.read_csv(f'{DATA_DIR}/large_r_logcounts.csv').values
r_W = pd.read_csv(f'{DATA_DIR}/large_W.csv').values
r_idx = pd.read_csv(f'{DATA_DIR}/large_idx.csv').values.ravel() - 1
r_bs_bio = pd.read_csv(f'{DATA_DIR}/large_bs_xy_bio.csv').values
r_bs_ls = pd.read_csv(f'{DATA_DIR}/large_bs_xy_ls.csv').values

with open(f'{DATA_DIR}/large_r_time.txt') as f:
    r_time = float(f.read().strip())

ngenes, ncells = counts.shape
print(f"Data: {ngenes} genes x {ncells} cells")
print(f"R reference time: {r_time:.3f}s")

# %% [markdown]
# ## 2. Run Python SpaNorm

# %%
from benchmark_optimized import run_optimized

# Warmup
run_optimized(counts, r_W, r_idx, max_iter=2, tol=1e10)

# 5 runs for timing
times = []
for i in range(5):
    gmean, alpha, psi, elapsed, iters = run_optimized(counts, r_W, r_idx, max_iter=30, tol=1e-4)
    times.append(elapsed)

py_time = np.mean(times)
print(f"Python avg time: {py_time:.3f}s (5 runs)")
print(f"Speedup: {r_time/py_time:.1f}x")

# %% [markdown]
# ## 3. Compute Normalized Output

# %%
W = r_W
n_bio = r_bs_bio.shape[1]
is_bio = np.array([False] + [True]*n_bio + [False]*(W.shape[1]-1-n_bio))
lmu_bio = np.clip(gmean[:, None] + alpha[:, is_bio] @ W[:, is_bio].T, -50, 50)
py_lc = np.log2(np.exp(lmu_bio))

# %% [markdown]
# ## 4. Parity Comparison

# %%
# Overall correlation
corr = np.corrcoef(r_lc.ravel(), py_lc.ravel())[0, 1]
print(f"Overall correlation: {corr:.6f}")

# Per-gene correlation
gene_corrs = np.zeros(ngenes)
for g in range(ngenes):
    if np.std(r_lc[g]) > 0 and np.std(py_lc[g]) > 0:
        gene_corrs[g] = np.corrcoef(r_lc[g], py_lc[g])[0, 1]

print(f"Per-gene mean: {np.mean(gene_corrs):.6f}")
print(f"Per-gene min:  {np.min(gene_corrs):.6f}")
print(f"Per-gene max:  {np.max(gene_corrs):.6f}")

# Model parameters
r_gmean = pd.read_csv(f'{DATA_DIR}/large_r_gmean.csv').values.ravel()
r_alpha = pd.read_csv(f'{DATA_DIR}/large_r_alpha.csv').values
r_psi = pd.read_csv(f'{DATA_DIR}/large_r_psi.csv').values.ravel()

print(f"\ngmean correlation: {np.corrcoef(r_gmean, gmean)[0,1]:.6f}")
print(f"alpha correlation: {np.corrcoef(r_alpha.ravel(), alpha.ravel())[0,1]:.6f}")
print(f"psi correlation:   {np.corrcoef(r_psi, psi)[0,1]:.6f}")

# %% [markdown]
# ## 5. Gate Check

# %%
print(f"Correlation: {corr:.6f} {'PASS' if corr > 0.96 else 'FAIL'} (threshold: 0.96)")
print(f"Speed:       {py_time:.3f}s {'PASS' if py_time < r_time else 'FAIL'} (R: {r_time:.3f}s)")
